baseURL = "/"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "30 Days Python & Flask"
theme = "hugo-theme-learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

[params]
  editURL = "https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/"
  description = "30 Days Python & Flask"
  author = "Chien Nguyen"
  showVisitedLinks = true
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "blue"

[outputs]
home = [ "HTML", "RSS", "JSON"]
